---
name: manageiq
directory: upstream
manageiq_git_url: https://github.com/ManageIQ/manageiq.git
appliance_git_url: https://github.com/ManageIQ/manageiq-appliance.git
targets:
  # Format:
  #   target: img_fac_target
  vsphere: vsphere
  ovirt: rhevm
  openstack: openstack-kvm
